### ISSUE TITLE
Failed to run Gulpfile.js

### ISSUE THREAD

**Issue by vsg24** [fourlabsldn/dep-linker#1]
When loading dep-linker into my Gulpfile.js, it throws the following error:

```
Failed to run "C:\Path\To\Project\gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\Path\To\Project\node_modules\dep-linker\index.js:19
  getPackageJson(root = this.projectRoot) {
                      ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Path\To\Project\gulpfile.js:12:17)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

Opening the index.js file in Visual Studio shows that visual studio can't recognize ES6 default parameter and it shows error but I can't see how that could affect gulp.

Here's my entire dev-dependencies:

```
"devDependencies": {
    "dep-linker": "^1.0.24",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-cssmin": "^0.1.7",
    "gulp-rename": "^1.2.2",
    "gulp-uglify": "^1.5.4",
    "rimraf": "^2.5.2"
  }
```

**Comment by lazamar** [comment]
Unfortunately, at the moment you need to have Node 6.0 or higher because of the non-transpiled ES6 code.
